[project]
name = "ai-agents-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.13.0",
    "langchain-community>=0.3.29",
    "wikipedia>=1.4.0",
]
